import {
	BookOpen,
	Building2,
	Download,
	Plus,
	Search,
	Users,
	LibraryBig,
	BarChart3,
	Settings,
} from "lucide-react";
import PageTitle from "./pageTitle.jsx";

const config = {
	libraries: {
		title: "Libraries",
		description: "Manage all registered libraries across the network.",
		icon: Building2,
		columns: [ "Library", "Location", "Members", "Books", "Status" ],
		rows: [
			[ "Unity Public Library", "Adama", "1,520", "7,300", "Active" ],
			[ "Bluebird Library", "Addis Ababa", "920", "4,810", "Active" ],
			[
				"Kora Research Library",
				"Dire Dawa",
				"1,880",
				"9,100",
				"Suspended",
			],
		],
	},
	users: {
		title: "Members & users",
		description: "Manage member accounts, administrators, and access.",
		icon: Users,
		columns: [ "Name", "Email", "Library", "Role", "Status" ],
		rows: [
			[
				"Amanuel Worku",
				"amanuel@example.com",
				"Unity Public",
				"Member",
				"Active",
			],
			[
				"Selamawit Tadesse",
				"selam@example.com",
				"Bluebird",
				"Librarian",
				"Active",
			],
			[
				"Yared Bekele",
				"yared@example.com",
				"Kora Research",
				"Member",
				"Blocked",
			],
		],
	},
	books: {
		title: "Books & catalog",
		description: "Monitor the shared catalog and inventory.",
		icon: BookOpen,
		columns: [ "Book", "Author", "Library", "Copies", "Availability" ],
		rows: [
			[ "Atomic Habits", "James Clear", "Unity Public", "24", "Available" ],
			[ "Clean Code", "Robert Martin", "Bluebird", "12", "8 available" ],
			[
				"The Pragmatic Programmer",
				"Hunt & Thomas",
				"Kora Research",
				"9",
				"2 available",
			],
		],
	},
	borrowing: {
		title: "Borrowing",
		description: "Track circulation, returns, overdue items, and fines.",
		icon: LibraryBig,
		columns: [ "Member", "Book", "Library", "Borrowed", "Due", "Status" ],
		rows: [
			[
				"Amanuel Worku",
				"Atomic Habits",
				"Unity Public",
				"Aug 4",
				"Aug 18",
				"On time",
			],
			[
				"Liya Abebe",
				"Clean Code",
				"Bluebird",
				"Jul 20",
				"Aug 3",
				"Overdue",
			],
			[
				"Dawit Girma",
				"The Pragmatic Programmer",
				"Kora Research",
				"Aug 7",
				"Aug 21",
				"On time",
			],
		],
	},
	reports: {
		title: "Reports & analytics",
		description: "Operational reports for the library network.",
		icon: BarChart3,
		columns: [ "Report", "Period", "Generated by", "Updated" ],
		rows: [
			[ "Monthly circulation", "July 2026", "System", "Aug 1" ],
			[ "Library growth", "Q2 2026", "System", "Jul 1" ],
			[ "Overdue accounts", "August 2026", "FRAOL", "Today" ],
		],
	},
	settings: {
		title: "Settings",
		description: "Configure your admin workspace and platform preferences.",
		icon: Settings,
		columns: [],
		rows: [],
	},
};
export function Generic({ type }) {
	const c = config[ type ] ?? config.libraries;
	const Icon = c.icon;

	const settingSections =
		[
			"General settings",
			"Notifications",
			"Admin roles & permissions",
			"Security",
		];

	return (
		<div>
			<PageTitle
				title={c.title}
				description={c.description}
				action={
					<button className="flex items-center gap-2 rounded-xl bg-surface px-4 py-2.5 text-sm font-semibold text-text">
						<Plus size={16} />
						Create
					</button>
				}
			/>
			{type === "settings" ? (
				<div className="grid gap-5 lg:grid-cols-2">
					{settingSections.map(function handleSettings(sections) {
						return (
							<div
								key={sections}
								className="rounded-2xl border border-border bg-surface p-6 shadow-sm">
								<div className="flex items-center gap-3">
									<div className="grid size-10 place-items-center rounded-xl bg-surface">
										<Icon size={18} />
									</div>
									<div>
										<h2 className="font-semibold">{sections}</h2>
										<p className="mt-1 text-xs text-text-muted">
											Configure {sections.toLowerCase()} for your
											organization.
										</p>
									</div>
								</div>
								<div className="mt-6 h-10 rounded-xl bg-surface-raised" />
							</div>

						);
					})}
				</div>
			) : (
				<div className="overflow-hidden rounded-2xl border border-border bg-surface shadow-sm">
					<div className="flex flex-col gap-3 border-b border-border p-4 sm:flex-row">
						<div className="relative flex-1">
							<Search
								size={16}
								className="absolute left-3 top-1/2 -translate-y-1/2 text-text-muted"
							/>
							<input
								placeholder="Search..."
								className="w-full rounded-xl bg-surface-raised py-2.5 pl-9 pr-4 text-sm outline-none focus:bg-surface focus:ring-2 focus:ring-accent"
							/>
						</div>
						<button className="flex items-center justify-center gap-2 rounded-xl border border-border px-4 py-2 text-sm font-semibold">
							<Download size={16} />
							Export
						</button>
					</div>
					<div className="overflow-x-auto">
						<table className="w-full min-w-175 text-left text-sm">
							<thead className="bg-surface text-xs uppercase text-text-muted">
								<tr>
									{c.columns.map(function handleColumns(column) {
										return (
											<th key={column} className="px-5 py-3">
												{column}
											</th>
										);
									})}
								</tr>
							</thead>
							<tbody className="divide-y divide-bg-surface">
								{c.rows.map((row, i) => (
									<tr key={i} className="hover:bg-accent">
										{row.map((x, j) => (
											<td
												key={j}
												className={`px-5 py-4 ${j === 0 ? "font-semibold" : "text-text-muted"}`}>
												{x}
											</td>
										))}
									</tr>
								))}
							</tbody>
						</table>
					</div>
				</div>
			)}
		</div>
	);
}
