// Scholar's Ledger management views: catalogue, branch, and loan-desk actions resolve through validated record forms and contextual menus.
import { BookPlus, Clipboard, FileText, Filter, ListFilter, LoaderCircle, Pencil, Plus, RefreshCw, Trash2, UserRound } from "lucide-react";
import { useState } from "react";
import { ActionMenu } from "@/components/ActionMenu";
import { BookForm, DeleteConfirmation, LibraryForm, RentalForm } from "@/components/EntityForms";
import { Panel, SearchBox, StatusPill, TableEmpty } from "@/components/DashboardPieces";

function SlimMetrics({ items }) { return <div className="metric-slim-row">{items.map((item) => <div key={item.label}><span>{item.label}</span><strong className={item.tone || ""}>{item.value}</strong></div>)}</div>; }
function withNotice(onNotice, success) { return { onSuccess: (result) => onNotice(success(result)) }; }
function Busy({ active, size = 14 }) { return active ? <LoaderCircle className="mutation-spinner" size={size} /> : null; }

export function LibrariesView({ data, onNotice, mutations }) {
  const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [libraryFormOpen, setLibraryFormOpen] = useState(false); const shown = data.libraries.filter((library) => (status === "all" || library.status === status) && `${library.name} ${library.city} ${library.branch}`.toLowerCase().includes(query.toLowerCase()));
  function createLibrary(values, callbacks = {}) { mutations.createLibrary.mutate(values, { onSuccess: (library) => { onNotice(`${library.name} was registered in the library network.`); callbacks.onSuccess?.(library); }, onError: callbacks.onError }); }
  function toggleStatus(library) { const nextStatus = library.status === "maintenance" ? "active" : "maintenance"; mutations.updateLibrary.mutate({ libraryId: library.id, changes: { status: nextStatus } }, withNotice(onNotice, () => `${library.name} is now marked ${nextStatus}.`)); }
  return <div className="page"><SlimMetrics items={[{ label: "Branches", value: data.libraries.length }, { label: "Total membership", value: data.libraries.reduce((sum, library) => sum + library.members, 0).toLocaleString() }, { label: "Service health", value: `${data.libraries.filter((library) => library.status === "active").length}/${data.libraries.length} active` }]} />
    <Panel title="Branch register" meta="Location, membership, plan, and operational status." action={<button className="primary-button compact" onClick={() => setLibraryFormOpen(true)}><Plus size={16} /> Add library</button>}><div className="table-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search libraries, branches, or cities…" /><label className="select-box"><ListFilter size={15} /><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All statuses</option><option value="active">Active</option><option value="maintenance">Maintenance</option></select></label></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Library</th><th>Location</th><th>Members</th><th>Collection</th><th>Plan</th><th>Status</th><th /></tr></thead><tbody>{shown.map((library) => <tr key={library.id}><td><strong>{library.name}</strong><small>{library.libraryType === "branch" ? `${library.branch} branch` : library.branch}</small></td><td>{library.city}, {library.state}</td><td>{library.members.toLocaleString()}</td><td>{library.totalBooks.toLocaleString()} books</td><td><span className={`plan-badge ${library.subscriptionPlan}`}>{library.subscriptionPlan}</span></td><td><StatusPill status={library.status} /></td><td><button className="row-action" onClick={() => toggleStatus(library)} disabled={mutations.updateLibrary.isPending}><Busy active={mutations.updateLibrary.isPending} />{library.status === "maintenance" ? "Reopen" : "Pause"}</button></td></tr>)}</tbody></table>{!shown.length ? <TableEmpty message="No library branches match this search." /> : null}</div>
    </Panel><LibraryForm open={libraryFormOpen} onOpenChange={setLibraryFormOpen} libraries={data.libraries} onCreate={createLibrary} pending={mutations.createLibrary.isPending} /></div>;
}

export function BooksView({ data, onNotice, mutations, selectedLibrary }) {
  const [query, setQuery] = useState(""); const [genre, setGenre] = useState("all"); const [condition, setCondition] = useState("all"); const [availableOnly, setAvailableOnly] = useState(false); const [bookFormOpen, setBookFormOpen] = useState(false); const [editingBook, setEditingBook] = useState(null); const [deletingBook, setDeletingBook] = useState(null);
  const genres = [...new Set(data.books.map((book) => book.genre))]; const shown = data.books.filter((book) => (genre === "all" || book.genre === genre) && (condition === "all" || book.condition === condition) && (!availableOnly || book.availableCopies > 0) && `${book.title} ${book.author} ${book.isbn} ${book.shelfLocation}`.toLowerCase().includes(query.toLowerCase())); const allCopies = data.books.reduce((sum, book) => sum + book.totalCopies, 0); const available = data.books.reduce((sum, book) => sum + book.availableCopies, 0);
  function createBook(values, callbacks = {}) { mutations.createBook.mutate(values, { onSuccess: (book) => { onNotice(`${book.title} was added to the catalogue.`); callbacks.onSuccess?.(book); }, onError: callbacks.onError }); }
  function updateBook(bookId, values, callbacks = {}) { mutations.updateBook.mutate({ bookId, changes: values }, { onSuccess: (book) => { onNotice(`${book.title} was revised.`); callbacks.onSuccess?.(book); }, onError: callbacks.onError }); }
  function restockBook(book) { mutations.updateBook.mutate({ bookId: book.id, changes: { availableCopies: Math.min(book.totalCopies, book.availableCopies + 1) } }, withNotice(onNotice, () => `${book.title} inventory was updated.`)); }
  function confirmDelete() { if (!deletingBook) return; mutations.deleteBook.mutate(deletingBook.id, { onSuccess: (book) => { onNotice(`${book.title} was removed from the catalogue.`); setDeletingBook(null); } }); }
  function openEdit(book) { setEditingBook(book); setBookFormOpen(true); } function closeBookForm(open) { setBookFormOpen(open); if (!open) setEditingBook(null); }
  return <div className="page"><SlimMetrics items={[{ label: "Titles in view", value: data.books.length }, { label: "Total copies", value: allCopies.toLocaleString() }, { label: "Available today", value: available.toLocaleString(), tone: "sage-text" }, { label: "Loaned out", value: (allCopies - available).toLocaleString() }]} />
    <Panel title="Collection register" meta={`${shown.length} records match the current discovery filters.`} action={<button className="primary-button compact" onClick={() => { setEditingBook(null); setBookFormOpen(true); }}><BookPlus size={16} /> Add book</button>}><div className="table-toolbar wrap record-discovery-bar"><SearchBox value={query} onChange={setQuery} placeholder="Find title, author, ISBN, or shelf…" /><label className="select-box"><Filter size={15} /><select value={genre} onChange={(event) => setGenre(event.target.value)}><option value="all">All genres</option>{genres.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="select-box"><select value={condition} onChange={(event) => setCondition(event.target.value)}><option value="all">All conditions</option><option value="excellent">Excellent</option><option value="good">Good</option><option value="fair">Fair</option></select></label><label className="checkbox-line"><input type="checkbox" checked={availableOnly} onChange={(event) => setAvailableOnly(event.target.checked)} /><span>Available now</span></label></div>
      <div className="data-table-wrap"><table className="data-table books-table"><thead><tr><th>Title & author</th><th>Genre</th><th>Shelf</th><th>Availability</th><th>Condition</th><th>Record actions</th></tr></thead><tbody>{shown.map((book) => { const percent = Math.round((book.availableCopies / book.totalCopies) * 100); return <tr key={book.id}><td><strong>{book.title}</strong><small>{book.author} · {book.isbn}</small></td><td>{book.genre}</td><td><code>{book.shelfLocation}</code></td><td><div className="availability-cell"><span>{book.availableCopies}/{book.totalCopies} copies</span><i><b className={percent === 0 ? "no-stock" : ""} style={{ width: `${percent}%` }} /></i></div></td><td><StatusPill status={book.condition} /></td><td><span className="row-actions"><button className="row-action" onClick={() => restockBook(book)} disabled={mutations.updateBook.isPending}><Busy active={mutations.updateBook.isPending} /> Restock</button><button className="row-icon-action" onClick={() => openEdit(book)} aria-label={`Edit ${book.title}`}><Pencil size={15} /></button><button className="row-icon-action danger" onClick={() => setDeletingBook(book)} aria-label={`Delete ${book.title}`}><Trash2 size={15} /></button></span></td></tr>; })}</tbody></table>{!shown.length ? <TableEmpty message="No books match the current search and filters." /> : null}</div>
    </Panel><BookForm open={bookFormOpen} onOpenChange={closeBookForm} libraries={data.libraries} selectedLibrary={selectedLibrary} book={editingBook} onCreate={createBook} onUpdate={updateBook} pending={mutations.createBook.isPending || mutations.updateBook.isPending} /><DeleteConfirmation open={Boolean(deletingBook)} onOpenChange={(open) => { if (!open) setDeletingBook(null); }} recordType="book" recordName={deletingBook?.title || "this book"} onConfirm={confirmDelete} pending={mutations.deleteBook.isPending} /></div>;
}

export function RentalsView({ data, onNotice, mutations, selectedLibrary, onMemberSelect, onDownloadRentalReceipt }) {
  const [query, setQuery] = useState(""); const [filter, setFilter] = useState("all"); const [rentalFormOpen, setRentalFormOpen] = useState(false); const count = (status) => status === "all" ? data.rentals.length : data.rentals.filter((rental) => rental.status === status).length; const shown = data.rentals.filter((rental) => (filter === "all" || rental.status === filter) && `${rental.memberName} ${rental.bookTitle}`.toLowerCase().includes(query.toLowerCase())); const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });
  function createRental(values, callbacks = {}) { mutations.createRental.mutate(values, { onSuccess: (rental) => { onNotice(`${rental.bookTitle} was issued to ${rental.memberName}.`); onDownloadRentalReceipt(rental); callbacks.onSuccess?.(rental); }, onError: callbacks.onError }); }
  function returnBook(rental) { mutations.returnRental.mutate({ rentalId: rental.id, input: {} }, withNotice(onNotice, () => `${rental.bookTitle} is marked returned.`)); }
  function renewBook(rental) { mutations.renewRental.mutate({ rentalId: rental.id, input: {} }, withNotice(onNotice, () => `${rental.bookTitle} was renewed.`)); }
  function loanMenu(rental) { return [{ label: "Renew loan", icon: RefreshCw, onSelect: () => renewBook(rental), disabled: mutations.renewRental.isPending }, { label: "Open member profile", icon: UserRound, onSelect: () => onMemberSelect(rental.memberName) }, { label: "Download receipt", icon: FileText, onSelect: () => onDownloadRentalReceipt(rental) }, { label: "Copy loan reference", icon: Clipboard, onSelect: () => onNotice(`Loan reference ${rental.id} is ready to copy.`) }]; }
  return <div className="page"><SlimMetrics items={[{ label: "Open loans", value: count("active") }, { label: "Overdue", value: count("overdue"), tone: "danger-text" }, { label: "Returned", value: count("returned") }, { label: "Outstanding fines", value: money.format(data.rentals.reduce((sum, rental) => sum + rental.fineAmount, 0)) }]} />
    <Panel title="Loan desk" meta="Review live circulation by patron, title, due date, and return status." action={<button className="primary-button compact" onClick={() => setRentalFormOpen(true)}><Plus size={16} /> New rental</button>}><div className="table-toolbar wrap"><div className="filter-tabs">{["all", "active", "overdue", "returned"].map((status) => <button key={status} onClick={() => setFilter(status)} className={filter === status ? "is-active" : ""}>{status === "all" ? "All loans" : status}<span>{count(status)}</span></button>)}</div><SearchBox value={query} onChange={setQuery} placeholder="Search reader or book…" /></div>
      <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Reader</th><th>Book</th><th>Rented</th><th>Due</th><th>Renewals</th><th>Fine</th><th>Status</th><th /></tr></thead><tbody>{shown.map((rental) => <tr key={rental.id}><td><button className="member-link" onClick={() => onMemberSelect(rental.memberName)}><strong>{rental.memberName}</strong><small>Open member profile</small></button></td><td><strong className="inline-strong">{rental.bookTitle}</strong></td><td>{rental.rentedDate}</td><td>{rental.dueDate}</td><td>{rental.renewalCount}</td><td className={rental.fineAmount ? "danger-text" : "muted-text"}>{rental.fineAmount ? `$${rental.fineAmount.toFixed(2)}` : "—"}</td><td><StatusPill status={rental.status} /></td><td>{rental.status === "active" || rental.status === "overdue" ? <span className="row-actions"><button className="row-action" onClick={() => returnBook(rental)} disabled={mutations.returnRental.isPending}><Busy active={mutations.returnRental.isPending} /> Return</button><ActionMenu label={`Actions for ${rental.bookTitle}`} items={loanMenu(rental)} /></span> : <span className="row-actions"><button className="row-action" onClick={() => onDownloadRentalReceipt(rental)}>Receipt</button><ActionMenu label={`Actions for ${rental.bookTitle}`} items={loanMenu(rental)} /></span>}</td></tr>)}</tbody></table>{!shown.length ? <TableEmpty message="No circulation records match this view." /> : null}</div>
    </Panel><RentalForm open={rentalFormOpen} onOpenChange={setRentalFormOpen} libraries={data.libraries} books={data.books} selectedLibrary={selectedLibrary} onCreate={createRental} pending={mutations.createRental.isPending} /></div>;
}
