// Scholar's Ledger operations views: people records now support search, status filtering, validated edits, and protected deletion.
import { CalendarCheck2, Check, Clipboard, Download, FileText, Filter, Pencil, Plus, ShieldCheck, SlidersHorizontal, Trash2 } from "lucide-react";
import { useState } from "react";
import { ActionMenu } from "@/components/ActionMenu";
import { DeleteConfirmation, TransactionForm, UserForm } from "@/components/EntityForms";
import { Panel, SearchBox, StatusPill, TableEmpty } from "@/components/DashboardPieces";

function SlimMetrics({ items }) { return <div className="metric-slim-row">{items.map((item) => <div key={item.label}><span>{item.label}</span><strong className={item.tone || ""}>{item.value}</strong></div>)}</div>; }
function withNotice(onNotice, success) { return { onSuccess: (result) => onNotice(success(result)) }; }
const money = new Intl.NumberFormat("en-US", { style: "currency", currency: "USD", maximumFractionDigits: 0 });

export function StaffView({ data, onNotice, mutations, selectedLibrary }) {
  const [query, setQuery] = useState(""); const [department, setDepartment] = useState("all"); const [status, setStatus] = useState("all"); const [mode, setMode] = useState("table"); const [userFormOpen, setUserFormOpen] = useState(false); const [editingUser, setEditingUser] = useState(null); const [deletingUser, setDeletingUser] = useState(null);
  const departments = [...new Set(data.staff.map((staff) => staff.department))]; const shown = data.staff.filter((staff) => (department === "all" || staff.department === department) && (status === "all" || staff.status === status) && `${staff.name} ${staff.email || ""} ${staff.role} ${staff.department}`.toLowerCase().includes(query.toLowerCase()));
  function createUser(values, callbacks = {}) { mutations.createStaffMember.mutate(values, { onSuccess: (staff) => { onNotice(`${staff.name} was added to the people register.`); callbacks.onSuccess?.(staff); }, onError: callbacks.onError }); }
  function updateUser(userId, values, callbacks = {}) { mutations.updateStaffMember.mutate({ staffId: userId, changes: values }, { onSuccess: (staff) => { onNotice(`${staff.name} was revised.`); callbacks.onSuccess?.(staff); }, onError: callbacks.onError }); }
  function toggleStaffStatus(staff) { const nextStatus = staff.status === "active" ? "on-leave" : "active"; mutations.updateStaffMember.mutate({ staffId: staff.id, changes: { status: nextStatus } }, withNotice(onNotice, () => `${staff.name} is now marked ${nextStatus}.`)); }
  function openEdit(staff) { setEditingUser(staff); setUserFormOpen(true); }
  function closeUserForm(open) { setUserFormOpen(open); if (!open) setEditingUser(null); }
  function confirmDelete() { if (!deletingUser) return; mutations.deleteStaffMember.mutate(deletingUser.id, { onSuccess: (staff) => { onNotice(`${staff.name} was removed from the people register.`); setDeletingUser(null); } }); }
  return <div className="page"><SlimMetrics items={[{ label: "Team members", value: data.staff.length }, { label: "On duty", value: data.staff.filter((staff) => staff.status === "active").length, tone: "sage-text" }, { label: "Departments", value: departments.length }, { label: "Monthly payroll", value: money.format(data.staff.reduce((sum, staff) => sum + staff.salary / 12, 0)) }]} />
    <Panel title="People and roles" meta={`${shown.length} users match the current discovery filters.`} action={<button className="primary-button compact" onClick={() => { setEditingUser(null); setUserFormOpen(true); }}><Plus size={16} /> Add user</button>}><div className="table-toolbar wrap record-discovery-bar"><SearchBox value={query} onChange={setQuery} placeholder="Find name, email, role, or department…" /><label className="select-box"><Filter size={15} /><select value={department} onChange={(event) => setDepartment(event.target.value)}><option value="all">All departments</option>{departments.map((item) => <option key={item} value={item}>{item}</option>)}</select></label><label className="select-box"><select value={status} onChange={(event) => setStatus(event.target.value)}><option value="all">All user statuses</option><option value="active">Active</option><option value="on-leave">On leave</option></select></label><div className="view-toggle"><button className={mode === "cards" ? "is-active" : ""} onClick={() => setMode("cards")}>Cards</button><button className={mode === "table" ? "is-active" : ""} onClick={() => setMode("table")}>Table</button></div></div>
      {mode === "cards" ? <div className="staff-card-grid">{shown.map((staff) => <article className="staff-card" key={staff.id}><div className="staff-card-top"><span className="staff-avatar large" style={{ backgroundColor: staff.avatarColor }}>{staff.initials}</span><StatusPill status={staff.status} /></div><h3>{staff.name}</h3><p>{staff.role}</p><div><span>{staff.department}</span><span className="card-record-actions"><button className="inline-button" onClick={() => openEdit(staff)}><Pencil size={12} /> Edit</button><button className="inline-button danger" onClick={() => setDeletingUser(staff)}><Trash2 size={12} /> Delete</button></span></div></article>)}</div> : <div className="data-table-wrap"><table className="data-table"><thead><tr><th>Team member</th><th>Role</th><th>Department</th><th>Annual salary</th><th>Status</th><th>Record actions</th></tr></thead><tbody>{shown.map((staff) => <tr key={staff.id}><td><div className="table-person"><span className="staff-avatar" style={{ backgroundColor: staff.avatarColor }}>{staff.initials}</span><span><strong>{staff.name}</strong><small>{staff.email || "Profile email pending"}</small></span></div></td><td>{staff.role}</td><td>{staff.department}</td><td>{money.format(staff.salary)}</td><td><StatusPill status={staff.status} /></td><td><span className="row-actions"><button className="row-action" onClick={() => toggleStaffStatus(staff)} disabled={mutations.updateStaffMember.isPending}>{staff.status === "active" ? "Leave" : "Activate"}</button><button className="row-icon-action" onClick={() => openEdit(staff)} aria-label={`Edit ${staff.name}`}><Pencil size={15} /></button><button className="row-icon-action danger" onClick={() => setDeletingUser(staff)} aria-label={`Delete ${staff.name}`}><Trash2 size={15} /></button></span></td></tr>)}</tbody></table></div>}{!shown.length ? <TableEmpty message="No people records match the current search and filters." /> : null}
    </Panel><UserForm open={userFormOpen} onOpenChange={closeUserForm} libraries={data.libraries} selectedLibrary={selectedLibrary} user={editingUser} onCreate={createUser} onUpdate={updateUser} pending={mutations.createStaffMember.isPending || mutations.updateStaffMember.isPending} /><DeleteConfirmation open={Boolean(deletingUser)} onOpenChange={(open) => { if (!open) setDeletingUser(null); }} recordType="user" recordName={deletingUser?.name || "this user"} onConfirm={confirmDelete} pending={mutations.deleteStaffMember.isPending} /></div>;
}

export function FinancesView({ data, onNotice, mutations, selectedLibrary, onDownloadTransactionReceipt }) {
  const [transactionFormOpen, setTransactionFormOpen] = useState(false); const income = data.transactions.filter((transaction) => transaction.type === "income").reduce((sum, transaction) => sum + transaction.amount, 0); const expenses = data.transactions.filter((transaction) => transaction.type === "expense").reduce((sum, transaction) => sum + transaction.amount, 0); const categories = data.transactions.filter((transaction) => transaction.type === "income"); const peak = Math.max(...categories.map((transaction) => transaction.amount), 1);
  function createTransaction(values, callbacks = {}) { mutations.createTransaction.mutate(values, { onSuccess: (transaction) => { onNotice(`${transaction.description} was posted to the financial ledger.`); onDownloadTransactionReceipt(transaction); callbacks.onSuccess?.(transaction); }, onError: callbacks.onError }); }
  return <div className="page"><SlimMetrics items={[{ label: "Income", value: money.format(income), tone: "sage-text" }, { label: "Expenses", value: money.format(expenses) }, { label: "Net result", value: money.format(income - expenses), tone: income >= expenses ? "sage-text" : "danger-text" }]} />
    <div className="finance-grid"><Panel title="Monthly operating trend" meta="Income and expenditure across the current cycle." action={<button className="icon-action" aria-label="Finance filters"><SlidersHorizontal size={18} /></button>}><div className="bar-chart"><div className="chart-key"><span><i className="income-dot" /> Income</span><span><i className="expense-dot" /> Expenses</span></div><div className="bars">{data.monthly.map((entry) => <div className="month-bar" key={entry.month}><div className="bar-pair"><i className="income-bar" style={{ height: `${(entry.income / 57070) * 100}%` }} /><i className="expense-bar" style={{ height: `${(entry.expenses / 57070) * 100}%` }} /></div><span>{entry.month}</span></div>)}</div></div></Panel><Panel title="Income sources" meta="Current month by category."><div className="category-list">{categories.map((transaction) => <div key={transaction.id}><span><strong>{transaction.category}</strong><small>{money.format(transaction.amount)}</small></span><i><b style={{ width: `${(transaction.amount / peak) * 100}%` }} /></i></div>)}</div></Panel></div>
    <Panel title="Transaction ledger" meta="The newest financial records within the selected scope." action={<div className="heading-actions"><button className="secondary-button compact" onClick={() => onNotice("Export will be enabled when the connected backend can generate a ledger file.")}><Download size={15} /> Export</button><button className="primary-button compact" onClick={() => setTransactionFormOpen(true)}><Plus size={15} /> Add entry</button></div>}><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Description</th><th>Category</th><th>Date</th><th>Direction</th><th>Amount</th><th /></tr></thead><tbody>{data.transactions.map((transaction) => <tr key={transaction.id}><td><strong>{transaction.description}</strong></td><td>{transaction.category}</td><td>{transaction.date}</td><td><span className={`direction ${transaction.type}`}>{transaction.type === "income" ? "+ Income" : "− Expense"}</span></td><td className={transaction.type === "income" ? "sage-text" : "ink-text"}>{transaction.type === "income" ? "+" : "−"}{money.format(transaction.amount)}</td><td><button className="row-action" onClick={() => onDownloadTransactionReceipt(transaction)}>Receipt</button></td></tr>)}</tbody></table></div></Panel><TransactionForm open={transactionFormOpen} onOpenChange={setTransactionFormOpen} libraries={data.libraries} selectedLibrary={selectedLibrary} onCreate={createTransaction} pending={mutations.createTransaction.isPending} /></div>;
}

export function PayrollView({ data, onNotice, mutations, selectedLibrary }) {
  const [query, setQuery] = useState(""); const shown = data.payroll.filter((record) => `${record.staffName} ${record.role}`.toLowerCase().includes(query.toLowerCase())); const net = data.payroll.reduce((sum, record) => sum + record.netPay, 0); function processCurrentPayroll() { mutations.processPayroll.mutate({ libraryId: selectedLibrary?.id }, withNotice(onNotice, (records) => `${records.length} payroll records were processed through POST /api/payroll/process.`)); }
  return <div className="page"><SlimMetrics items={[{ label: "Current period", value: "Aug 2026" }, { label: "Records", value: data.payroll.length }, { label: "Net payroll", value: money.format(net) }, { label: "Ready to pay", value: data.payroll.filter((record) => record.status === "paid").length, tone: "sage-text" }]} /><Panel title="Payroll register" meta="Monthly record by staff member, department, and payment state." action={<div className="heading-actions"><button className="secondary-button compact" onClick={() => onNotice("Export is intentionally a placeholder until a backend generates the file.")}><Download size={15} /> Export</button><button className="primary-button compact" onClick={processCurrentPayroll} disabled={mutations.processPayroll.isPending}><Check size={15} /> {mutations.processPayroll.isPending ? "Processing…" : "Process payroll"}</button></div>}><div className="table-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search payroll records…" /></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Team member</th><th>Department</th><th>Hours</th><th>Gross pay</th><th>Deductions</th><th>Net pay</th><th>Status</th></tr></thead><tbody>{shown.map((record) => <tr key={record.id}><td><strong>{record.staffName}</strong><small>{record.role}</small></td><td>{record.department}</td><td>{record.hoursWorked} h</td><td>{money.format(record.grossPay)}</td><td>{money.format(record.totalDeductions)}</td><td><strong>{money.format(record.netPay)}</strong></td><td><StatusPill status={record.status} /></td></tr>)}</tbody><tfoot><tr><td colSpan="5">Total net payroll</td><td>{money.format(shown.reduce((sum, record) => sum + record.netPay, 0))}</td><td /></tr></tfoot></table>{!shown.length ? <TableEmpty message="No payroll records match this search." /> : null}</div></Panel></div>;
}

export function AttendanceView({ data, onNotice, mutations, selectedLibrary }) {
  const [date, setDate] = useState("2026-08-27"); const count = (status) => data.attendance.filter((record) => record.status === status).length; function recordCheckIn() { mutations.createAttendanceRecord.mutate({ staffName: "New check-in", role: "Library Assistant", checkIn: "09:00", checkOut: "—", date, libraryId: selectedLibrary?.id || data.libraries[0]?.id }, withNotice(onNotice, () => "A new check-in was created through POST /api/attendance.")); }
  function updateAttendance(record, changes) { mutations.updateAttendanceRecord.mutate({ attendanceId: record.id, changes }, withNotice(onNotice, () => `${record.staffName} attendance was updated.`)); }
  return <div className="page"><SlimMetrics items={[{ label: "Present", value: count("present"), tone: "sage-text" }, { label: "Late arrivals", value: count("late"), tone: "gold-text" }, { label: "Absent", value: count("absent"), tone: "danger-text" }, { label: "On leave", value: count("leave") }]} /><Panel title="Today’s attendance" meta="Wednesday, 27 August 2026." action={<div className="heading-actions"><label className="date-control"><CalendarCheck2 size={16} /><input type="date" value={date} onChange={(event) => setDate(event.target.value)} /></label><button className="secondary-button compact" onClick={() => onNotice("Export will be enabled when the connected backend can generate a file.")}><Download size={15} /> Export</button><button className="primary-button compact" onClick={recordCheckIn} disabled={mutations.createAttendanceRecord.isPending}><Plus size={15} /> Check in</button></div>}><div className="attendance-banner"><div><span className="notice-icon sage"><ShieldCheck size={17} /></span><span><strong>Coverage is healthy.</strong><small>Most colleagues are currently expected on site.</small></span></div><p>Selected date: {date}</p></div><div className="data-table-wrap"><table className="data-table"><thead><tr><th>Team member</th><th>Role</th><th>Check in</th><th>Check out</th><th>Today’s status</th><th /></tr></thead><tbody>{data.attendance.map((record) => <tr key={record.id}><td><strong>{record.staffName}</strong></td><td>{record.role}</td><td>{record.checkIn}</td><td>{record.checkOut}</td><td><StatusPill status={record.status} /></td><td><ActionMenu label={`Actions for ${record.staffName}`} items={[{ label: record.status === "present" ? "Mark late" : "Mark present", icon: CalendarCheck2, onSelect: () => updateAttendance(record, { status: record.status === "present" ? "late" : "present" }) }, { label: "Record note", icon: FileText, onSelect: () => onNotice(`Attendance note for ${record.staffName} is ready for review.`) }, { label: "Copy attendance ID", icon: Clipboard, onSelect: () => onNotice(`Attendance reference ${record.id} is ready to copy.`) }]} /></td></tr>)}</tbody></table></div></Panel></div>;
}
