// Scholar's Ledger record forms: creation and editing share one validated API-ready contract, while deletions require explicit confirmation.
import { zodResolver } from "@hookform/resolvers/zod";
import { AlertTriangle, Check, LoaderCircle, Pencil, Trash2 } from "lucide-react";
import { useEffect } from "react";
import { useForm } from "react-hook-form";
import { z } from "zod";
import { Dialog, DialogContent, DialogDescription, DialogFooter, DialogHeader, DialogTitle } from "@/components/ui/dialog";

const bookSchema = z.object({
  title: z.string().trim().min(2, "Enter a title of at least 2 characters.").max(140, "Keep the title under 140 characters."),
  author: z.string().trim().min(2, "Enter the author’s name.").max(100, "Keep the author under 100 characters."),
  isbn: z.string().trim().min(10, "Enter a valid ISBN or catalogue identifier.").max(32, "Keep the identifier under 32 characters."),
  genre: z.string().trim().min(2, "Select or enter a genre."),
  shelfLocation: z.string().trim().min(2, "Enter a shelf location.").max(20, "Keep the shelf code under 20 characters."),
  totalCopies: z.coerce.number().int().min(1, "At least one copy is required.").max(9999, "Enter fewer than 10,000 copies."),
  availableCopies: z.coerce.number().int().min(0, "Available copies cannot be negative."),
  condition: z.enum(["excellent", "good", "fair"]), libraryId: z.string().min(1, "Choose a library branch."),
}).refine((values) => values.availableCopies <= values.totalCopies, { path: ["availableCopies"], message: "Available copies cannot exceed total copies." });

const userSchema = z.object({
  name: z.string().trim().min(2, "Enter the user’s name.").max(80, "Keep the name under 80 characters."), email: z.string().trim().email("Enter a valid email address."), role: z.string().trim().min(2, "Enter a role."), department: z.string().trim().min(2, "Enter a department."), salary: z.coerce.number().int().min(0, "Salary cannot be negative.").max(1_000_000, "Enter a realistic annual salary."), libraryId: z.string().min(1, "Choose a library branch."),
});

const librarySchema = z.object({
  name: z.string().trim().min(3, "Enter a library name.").max(100, "Keep the name under 100 characters."), libraryType: z.enum(["main", "branch"]), parentLibraryId: z.string().optional(), branch: z.string().trim().min(2, "Enter a branch designation.").max(80, "Keep the branch name under 80 characters."), city: z.string().trim().min(2, "Enter the city."), state: z.string().trim().min(2, "Enter the state or region."), subscriptionPlan: z.enum(["basic", "pro", "enterprise"]),
}).superRefine((values, context) => { if (values.libraryType === "branch" && !values.parentLibraryId) context.addIssue({ code: "custom", path: ["parentLibraryId"], message: "Select the main library that this branch belongs to." }); });
const rentalSchema = z.object({
  memberName: z.string().trim().min(2, "Enter the member’s name."), memberEmail: z.string().trim().email("Enter a valid member email."), libraryId: z.string().min(1, "Choose a lending branch."), bookId: z.string().min(1, "Select an available book."), dueDate: z.string().min(1, "Choose a due date."),
});
const transactionSchema = z.object({
  type: z.enum(["income", "expense"]), category: z.string().trim().min(2, "Enter a transaction category."), description: z.string().trim().min(3, "Enter a useful ledger description.").max(140, "Keep the description under 140 characters."), amount: z.coerce.number().positive("Enter an amount greater than zero.").max(1_000_000, "Enter a realistic amount."), date: z.string().min(1, "Choose an entry date."), libraryId: z.string().min(1, "Choose the affected branch."),
});

function defaultBook(libraryId) { return { title: "", author: "", isbn: "", genre: "Fiction", shelfLocation: "", totalCopies: 1, availableCopies: 1, condition: "good", libraryId: libraryId || "" }; }
function defaultUser(libraryId) { return { name: "", email: "", role: "Library Assistant", department: "Circulation", salary: 0, libraryId: libraryId || "" }; }
function defaultLibrary(libraries) { return { name: "", libraryType: "main", parentLibraryId: libraries[0]?.id || "", branch: "Main Library", city: "", state: "", subscriptionPlan: "basic" }; }
function defaultRental(libraryId) { return { memberName: "", memberEmail: "", libraryId: libraryId || "", bookId: "", dueDate: "" }; }
function defaultTransaction(libraryId) { return { type: "income", category: "Membership fees", description: "", amount: "", date: new Date().toISOString().slice(0, 10), libraryId: libraryId || "" }; }
function bookValues(book, libraryId) { return book ? { ...defaultBook(libraryId), ...book } : defaultBook(libraryId); }
function userValues(user, libraryId) { return user ? { ...defaultUser(libraryId), ...user, email: user.email || `${user.initials?.toLowerCase() || "user"}@libracore.local` } : defaultUser(libraryId); }
function Field({ label, error, children, hint }) { return <label className="entity-field"><span>{label}</span>{children}{hint ? <small>{hint}</small> : null}{error ? <em role="alert">{error.message}</em> : null}</label>; }
function BranchOptions({ libraries }) { return <>{libraries.map((library) => <option key={library.id} value={library.id}>{library.name} — {library.branch}</option>)}</>; }
function FormSubmit({ pending, label }) { return <button className="primary-button" disabled={pending} type="submit">{pending ? <LoaderCircle className="mutation-spinner" size={16} /> : <Check size={16} />}{pending ? "Saving…" : label}</button>; }

export function BookForm({ open, onOpenChange, libraries, selectedLibrary, book, onCreate, onUpdate, pending }) {
  const editing = Boolean(book); const branchId = selectedLibrary?.id || libraries[0]?.id;
  const form = useForm({ resolver: zodResolver(bookSchema), defaultValues: bookValues(book, branchId) });
  useEffect(() => { if (open) form.reset(bookValues(book, branchId)); }, [open, book, branchId, form]);
  function submit(values) { const callbacks = { onSuccess: () => { form.reset(bookValues(null, branchId)); onOpenChange(false); } }; if (editing) onUpdate(book.id, values, callbacks); else onCreate(values, callbacks); }
  const { register, handleSubmit, formState: { errors } } = form;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="entity-dialog"><DialogHeader><p className="form-kicker">Catalogue intake / {editing ? "record revision" : "new record"}</p><DialogTitle>{editing ? "Edit book record" : "Add a book"}</DialogTitle><DialogDescription>{editing ? "Update the catalogue details before the revision is patched to the collection endpoint." : "Complete the record before it is posted to the collection endpoint."}</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)} noValidate><div className="entity-form-grid"><Field label="Title" error={errors.title}><input autoFocus {...register("title")} placeholder="e.g. The Archive of Lost Hours" /></Field><Field label="Author" error={errors.author}><input {...register("author")} placeholder="e.g. Clara Hayes" /></Field><Field label="ISBN / identifier" error={errors.isbn}><input {...register("isbn")} placeholder="978-0-0000-0000-0" /></Field><Field label="Genre" error={errors.genre}><input {...register("genre")} placeholder="Fiction" /></Field><Field label="Shelf location" error={errors.shelfLocation} hint="Use the local catalogue shelf code."><input {...register("shelfLocation")} placeholder="F-A01" /></Field><Field label="Condition" error={errors.condition}><select {...register("condition")}><option value="excellent">Excellent</option><option value="good">Good</option><option value="fair">Fair</option></select></Field><Field label="Total copies" error={errors.totalCopies}><input type="number" min="1" {...register("totalCopies")} /></Field><Field label="Available copies" error={errors.availableCopies}><input type="number" min="0" {...register("availableCopies")} /></Field><Field label="Library branch" error={errors.libraryId}><select {...register("libraryId")}><option value="">Choose a branch</option><BranchOptions libraries={libraries} /></select></Field></div><DialogFooter className="entity-footer"><button type="button" className="secondary-button" onClick={() => onOpenChange(false)} disabled={pending}>Cancel</button><FormSubmit pending={pending} label={editing ? "Save revision" : "Add to catalogue"} /></DialogFooter></form></DialogContent></Dialog>;
}

export function UserForm({ open, onOpenChange, libraries, selectedLibrary, user, onCreate, onUpdate, pending }) {
  const editing = Boolean(user); const branchId = selectedLibrary?.id || libraries[0]?.id;
  const form = useForm({ resolver: zodResolver(userSchema), defaultValues: userValues(user, branchId) });
  useEffect(() => { if (open) form.reset(userValues(user, branchId)); }, [open, user, branchId, form]);
  function submit(values) { const initials = values.name.split(/\s+/).map((part) => part[0]).join("").slice(0, 2).toUpperCase(); const payload = { ...values, initials }; const callbacks = { onSuccess: () => { form.reset(userValues(null, branchId)); onOpenChange(false); } }; if (editing) onUpdate(user.id, payload, callbacks); else onCreate({ ...payload, status: "active", avatarColor: "#2457D6" }, callbacks); }
  const { register, handleSubmit, formState: { errors } } = form;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="entity-dialog"><DialogHeader><p className="form-kicker">People register / {editing ? "profile revision" : "new user"}</p><DialogTitle>{editing ? "Edit team user" : "Add a team user"}</DialogTitle><DialogDescription>{editing ? "Update this user profile before the revision is patched to the people endpoint." : "Create the staff profile that will be posted to the people endpoint."}</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)} noValidate><div className="entity-form-grid"><Field label="Full name" error={errors.name}><input autoFocus {...register("name")} placeholder="e.g. Amara Okello" /></Field><Field label="Email address" error={errors.email}><input type="email" {...register("email")} placeholder="amara@example.com" /></Field><Field label="Role" error={errors.role}><input {...register("role")} placeholder="Reference Librarian" /></Field><Field label="Department" error={errors.department}><input {...register("department")} placeholder="Reference" /></Field><Field label="Annual salary" error={errors.salary}><input type="number" min="0" step="1000" {...register("salary")} /></Field><Field label="Library branch" error={errors.libraryId}><select {...register("libraryId")}><option value="">Choose a branch</option><BranchOptions libraries={libraries} /></select></Field></div><DialogFooter className="entity-footer"><button type="button" className="secondary-button" onClick={() => onOpenChange(false)} disabled={pending}>Cancel</button><FormSubmit pending={pending} label={editing ? "Save user" : "Create user"} /></DialogFooter></form></DialogContent></Dialog>;
}

export function DeleteConfirmation({ open, onOpenChange, recordType, recordName, onConfirm, pending }) {
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="entity-dialog delete-dialog"><DialogHeader><p className="form-kicker">Protected action / permanent removal</p><DialogTitle><AlertTriangle size={22} /> Delete {recordType}</DialogTitle><DialogDescription><strong>{recordName}</strong> will be permanently removed from the local record set. This action cannot be undone after it reaches your backend.</DialogDescription></DialogHeader><DialogFooter className="entity-footer"><button type="button" className="secondary-button" onClick={() => onOpenChange(false)} disabled={pending}>Keep {recordType}</button><button type="button" className="danger-button" onClick={onConfirm} disabled={pending}>{pending ? <LoaderCircle className="mutation-spinner" size={16} /> : <Trash2 size={16} />}{pending ? "Deleting…" : `Delete ${recordType}`}</button></DialogFooter></DialogContent></Dialog>;
}

export function LibraryForm({ open, onOpenChange, libraries, onCreate, pending }) {
  const form = useForm({ resolver: zodResolver(librarySchema), defaultValues: defaultLibrary(libraries) }); const libraryType = form.watch("libraryType");
  useEffect(() => { if (open) form.reset(defaultLibrary(libraries)); }, [open, libraries, form]);
  function submit(values) { onCreate({ ...values, parentLibraryId: values.libraryType === "branch" ? values.parentLibraryId : null, branch: values.libraryType === "main" ? "Main Library" : values.branch, members: 0, totalBooks: 0, staffCount: 0, status: "active", monthlyRevenue: 0 }, { onSuccess: () => { form.reset(defaultLibrary(libraries)); onOpenChange(false); } }); }
  const { register, handleSubmit, formState: { errors } } = form;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="entity-dialog"><DialogHeader><p className="form-kicker">Library network / new location</p><DialogTitle>Add a library</DialogTitle><DialogDescription>Register a new main library or connect a service branch to an existing location.</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)} noValidate><div className="entity-form-grid"><Field label="Library name" error={errors.name}><input autoFocus {...register("name")} placeholder="e.g. Southgate Public Library" /></Field><Field label="Library type" error={errors.libraryType}><select {...register("libraryType")}><option value="main">Main library</option><option value="branch">Branch library</option></select></Field>{libraryType === "branch" ? <Field label="Main library" error={errors.parentLibraryId}><select {...register("parentLibraryId")}><option value="">Choose the main library</option><BranchOptions libraries={libraries} /></select></Field> : <Field label="Network role" hint="This location is a top-level main library."><input value="Main Library" disabled /></Field>}<Field label="Branch designation" error={errors.branch}><input {...register("branch")} placeholder="e.g. Riverside Branch" disabled={libraryType === "main"} /></Field><Field label="City" error={errors.city}><input {...register("city")} placeholder="New York" /></Field><Field label="State or region" error={errors.state}><input {...register("state")} placeholder="NY" /></Field><Field label="Service plan" error={errors.subscriptionPlan}><select {...register("subscriptionPlan")}><option value="basic">Basic</option><option value="pro">Professional</option><option value="enterprise">Enterprise</option></select></Field></div><DialogFooter className="entity-footer"><button type="button" className="secondary-button" onClick={() => onOpenChange(false)} disabled={pending}>Cancel</button><FormSubmit pending={pending} label="Register library" /></DialogFooter></form></DialogContent></Dialog>;
}

export function RentalForm({ open, onOpenChange, libraries, books, selectedLibrary, onCreate, pending }) {
  const branchId = selectedLibrary?.id || libraries[0]?.id; const form = useForm({ resolver: zodResolver(rentalSchema), defaultValues: defaultRental(branchId) }); const libraryId = form.watch("libraryId"); const availableBooks = books.filter((book) => book.libraryId === libraryId && book.availableCopies > 0);
  useEffect(() => { if (open) form.reset(defaultRental(branchId)); }, [open, branchId, form]);
  function submit(values) { const book = books.find((item) => item.id === values.bookId); onCreate({ ...values, bookTitle: book?.title, rentedDate: new Date().toISOString().slice(0, 10), status: "active", renewalCount: 0, fineAmount: 0 }, { onSuccess: () => { form.reset(defaultRental(branchId)); onOpenChange(false); } }); }
  const { register, handleSubmit, formState: { errors } } = form;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="entity-dialog"><DialogHeader><p className="form-kicker">Circulation desk / new loan</p><DialogTitle>Open a rental</DialogTitle><DialogDescription>Record the reader, lending branch, available title, and agreed return date.</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)} noValidate><div className="entity-form-grid"><Field label="Member name" error={errors.memberName}><input autoFocus {...register("memberName")} placeholder="e.g. Robin Cole" /></Field><Field label="Member email" error={errors.memberEmail}><input type="email" {...register("memberEmail")} placeholder="robin@example.com" /></Field><Field label="Lending branch" error={errors.libraryId}><select {...register("libraryId")}><option value="">Choose a branch</option><BranchOptions libraries={libraries} /></select></Field><Field label="Available title" error={errors.bookId} hint={libraryId && !availableBooks.length ? "No available books at this branch." : "Only in-stock titles are listed."}><select {...register("bookId")}><option value="">Choose a title</option>{availableBooks.map((book) => <option key={book.id} value={book.id}>{book.title} — {book.availableCopies} available</option>)}</select></Field><Field label="Due date" error={errors.dueDate}><input type="date" {...register("dueDate")} /></Field></div><DialogFooter className="entity-footer"><button type="button" className="secondary-button" onClick={() => onOpenChange(false)} disabled={pending}>Cancel</button><FormSubmit pending={pending} label="Open rental" /></DialogFooter></form></DialogContent></Dialog>;
}

export function TransactionForm({ open, onOpenChange, libraries, selectedLibrary, onCreate, pending }) {
  const branchId = selectedLibrary?.id || libraries[0]?.id; const form = useForm({ resolver: zodResolver(transactionSchema), defaultValues: defaultTransaction(branchId) });
  useEffect(() => { if (open) form.reset(defaultTransaction(branchId)); }, [open, branchId, form]);
  function submit(values) { onCreate(values, { onSuccess: () => { form.reset(defaultTransaction(branchId)); onOpenChange(false); } }); }
  const { register, handleSubmit, formState: { errors } } = form;
  return <Dialog open={open} onOpenChange={onOpenChange}><DialogContent className="entity-dialog"><DialogHeader><p className="form-kicker">Financial ledger / new entry</p><DialogTitle>Add a financial entry</DialogTitle><DialogDescription>Enter the transaction direction, category, amount, and branch allocation before posting it to the ledger.</DialogDescription></DialogHeader><form onSubmit={handleSubmit(submit)} noValidate><div className="entity-form-grid"><Field label="Direction" error={errors.type}><select {...register("type")}><option value="income">Income</option><option value="expense">Expense</option></select></Field><Field label="Category" error={errors.category}><input {...register("category")} placeholder="e.g. Membership fees" /></Field><Field label="Description" error={errors.description}><input autoFocus {...register("description")} placeholder="e.g. Annual membership renewal" /></Field><Field label="Amount" error={errors.amount}><input type="number" min="0.01" step="0.01" {...register("amount")} placeholder="0.00" /></Field><Field label="Entry date" error={errors.date}><input type="date" {...register("date")} /></Field><Field label="Library branch" error={errors.libraryId}><select {...register("libraryId")}><option value="">Choose a branch</option><BranchOptions libraries={libraries} /></select></Field></div><DialogFooter className="entity-footer"><button type="button" className="secondary-button" onClick={() => onOpenChange(false)} disabled={pending}>Cancel</button><FormSubmit pending={pending} label="Post to ledger" /></DialogFooter></form></DialogContent></Dialog>;
}
